new gh action error handling

diff --git a/.github/workflows/master-pr-wf.yaml b/.github/workflows/master-pr-wf.yaml
--- a/.github/workflows/master-pr-wf.yaml
+++ b/.github/workflows/master-pr-wf.yaml
@@ -20,14 +20,9 @@ jobs:
           git tag ${{ env.VERSION }}
           if [ $? -ne 0 ]
           then
-            echo "TAG_EXISTS=1" >> $GITHUB_ENV
-          fi
-      - name: bio-api current version tag exists?
-        if: env.TAG_EXISTS == 1
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed('This bio-api version tag already exists in repository')          
+            echo "::error::This bio-api version tag already exists in repository"
+            exit 1
+          fi          
 
   version-check-docker:
     runs-on: ubuntu-latest
