New one line solution

diff --git a/.github/workflows/master-pr-wf.yaml b/.github/workflows/master-pr-wf.yaml
--- a/.github/workflows/master-pr-wf.yaml
+++ b/.github/workflows/master-pr-wf.yaml
@@ -16,13 +16,7 @@ jobs:
         run: SETTINGSFILE=$(pwd)/bio-api/bioapi.py ./tools/get_version.sh >> $GITHUB_ENV
       - name: Check if tag exist.
         shell: bash
-        run: |
-          git tag ${{ env.VERSION }}
-          if [ $? -ne 0 ]
-          then
-            echo "::error::This bio-api version tag already exists in repository"
-            exit 1
-          fi          
+        run: git tag ${{ env.VERSION }} 2>/dev/null || echo "::error::This bio-api version tag already exists in repository"   
 
   version-check-docker:
     runs-on: ubuntu-latest
