Update master-pr-wf.yaml

diff --git a/.github/workflows/master-pr-wf.yaml b/.github/workflows/master-pr-wf.yaml
--- a/.github/workflows/master-pr-wf.yaml
+++ b/.github/workflows/master-pr-wf.yaml
@@ -16,7 +16,8 @@ jobs:
         run: SETTINGSFILE=$(pwd)/bio-api/bioapi.py ./tools/get_version.sh >> $GITHUB_ENV
       - name: Check if tag exist.
         shell: bash
-        run: test -n "$(git tag -l ${{ env.VERSION }})" && echo "::error::This bio-api version tag already exists in repository." && exit 1
+        run: |
+          test -n "$(git tag -l ${{ env.VERSION }})" && echo "::error::This bio-api version tag already exists in repository." && exit 1
         
   version-check-docker:
     runs-on: ubuntu-latest
