new solution for check tag (#10)

diff --git a/.github/workflows/master-pr-wf.yaml b/.github/workflows/master-pr-wf.yaml
--- a/.github/workflows/master-pr-wf.yaml
+++ b/.github/workflows/master-pr-wf.yaml
@@ -9,31 +9,29 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       - name: Get version
         run: SETTINGSFILE=$(pwd)/bio-api/bioapi.py ./tools/get_version.sh
       - name: Set version
         run: SETTINGSFILE=$(pwd)/bio-api/bioapi.py ./tools/get_version.sh >> $GITHUB_ENV
-      - name: Check if tag exist.
-        shell: bash
+      - name: Check if tag exist 2
         run: |
-          git tag ${{ env.VERSION }}
-          if [ $? -ne 0 ]
+          TAG=$(git tag -l ${{ env.VERSION }})
+          if [ -n "$TAG" ]
           then
-            echo "TAG_EXISTS=1" >> $GITHUB_ENV
-          fi
-      - name: bio-api current version tag exists?
-        if: env.TAG_EXISTS == 1
-        uses: actions/github-script@v3
-        with:
-          script: |
-            core.setFailed('This bio-api version tag already exists in repository')          
+            echo "::error::This bio-api version tag ($TAG) already exists in repository."
+            exit 1
+          fi        
 
   version-check-docker:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
       - name: Get version
         run: SETTINGSFILE=$(pwd)/bio-api/bioapi.py ./tools/get_version.sh
       - name: Set version
